#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_workspace_id

arg_organization_name="${TF_CLOUD_ORGANIZATION:-}"
arg_workspace_name="${TF_WORKSPACE:-}"
httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Organizations" --id-glob='*' | \
      jq --raw-output 'map("--organization-name=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Organizations" --id-glob='*' | \
      jq --raw-output 'map("--organization-name=\(.attributes | fromjson | .name)") | unique[]'
    tfc-helper-cache-get --table="Workspaces" --id-glob='*' | \
      jq --raw-output 'map("--workspace-id=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Workspaces" --id-glob='*' | \
      jq --raw-output 'map("--workspace-name=\(.attributes | fromjson | .name)") | unique[]'
    exit 0
    ;;
  "--debug" )
    set -x
    ;;
  "--force" ) # option: refresh cache
    :
    ;;
  "--help" ) # option: display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--organization-name" | "--organization-name="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_organization_name="${1#*=}"
    else
      arg_organization_name="${2:-}"
      shift 1
    fi
    ;;
  "--workspace-id" | "--workspace-id="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_workspace_id="${1#*=}"
    else
      arg_workspace_id="${2:-}"
      shift 1
    fi
    ;;
  "--workspace-name" | "--workspace-name="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_workspace_name="${1#*=}"
    else
      arg_workspace_name="${2:-}"
      shift 1
    fi
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_organization_name:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: organization name was not given"
  exit 1
fi

if [[ -z "${arg_workspace_id:-}" ]]; then
  if [[ -z "${arg_workspace_name:-}" ]]; then
    :
  else
    arg_workspace_id="$(tfc-helper-cache-get --table="Workspaces" --id-glob='*' | \
      jq --arg name "${arg_workspace_name}" --raw-output 'map(select(.attributes | fromjson | .name == $name))[].id' \
    )"
  fi
  if [[ -z "${arg_workspace_id:-}" ]]; then
    tfc-helper-logger --level=error "${0##*/}: workspace name id not given"
    exit 1
  fi
fi

# https://developer.hashicorp.com/terraform/cloud-docs/api-docs/state-versions#list-state-versions-for-a-workspace
tfc-helper-httpclient --request-path="/state-versions" --data "filter[organization][name]=${arg_organization_name}" --data "filter[workspace][name]=${arg_workspace_name}" --get "${httpclient_args[@]}" | \
  tfc-helper-cache-set --table="StateVersions"
