#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/run#list-runs-in-a-workspace

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_workspace_id

arg_workspace_name="${TF_WORKSPACE:-}"

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    shift 1
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Workspaces" --id-glob='*' | \
      jq --raw-output 'map("--workspace-id=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Workspaces" --id-glob='*' | \
      jq --raw-output 'map("--workspace-name=\(.attributes | fromjson | .name)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--workspace-id" | "--workspace-id="* ) # option: Workspace ID
    if [[ "$1" == *"="* ]]; then
      arg_workspace_id="${1#*=}"
    else
      arg_workspace_id="${2:-}"
      shift 1
    fi
    ;;
  "--workspace-name" | "--workspace-name="* ) # option: Workspace name
    if [[ "$1" == *"="* ]]; then
      arg_workspace_name="${1#*=}"
    else
      arg_workspace_name="${2:-}"
      shift 1
    fi
    ;;
  "--verbose" | "-v" ) # option: Enable verbose output
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_workspace_id:-}" ]]; then
  if [[ -z "${arg_workspace_name:-}" ]]; then
    :
  else
    arg_workspace_id="$(tfc-get-workspace --workspace-name="${arg_workspace_name}" | jq --raw-output '.data.id')"
  fi
  if [[ -z "${arg_workspace_id:-}" ]]; then
    tfc-helper-logger --level=error "${0##*/}: workspace name was not given"
    exit 1
  fi
fi

# https://www.terraform.io/cloud-docs/api-docs/run#list-runs-in-a-workspace
tfc-helper-httpclient --request-path="/workspaces/${arg_workspace_id}/runs" | \
  tfc-helper-cache-set --partial --table="Runs"
