#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_id_glob
unset arg_id_value
unset arg_table

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    exit 0
    ;;
  "--id-glob" | "--id-glob="* ) # option: TBD
    if [[ "$1" == *"="* ]]; then
      arg_id_glob="${1#*=}"
    else
      arg_id_glob="${2:-}"
      shift 1
    fi
    ;;
  "--id-value" | "--id-value="* ) # option: TBD
    if [[ "$1" == *"="* ]]; then
      arg_id_value="${1#*=}"
    else
      arg_id_value="${2:-}"
      shift 1
    fi
    ;;
  "--table" | "--table="* ) # option: SQLite3 table name used for caching
    if [[ "$1" == *"="* ]]; then
      arg_table="${1#*=}"
    else
      arg_table="${2:-}"
      shift 1
    fi
    ;;
  "--verbose" ) # option: Enable verbose output
    export VERBOSE=1
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_id_glob:-}" ]] && [[ -z "${arg_id_value:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: missing required option: --id-glob or --id-value"
  exit
fi

if [[ -z "${arg_table:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: missing required option: --table"
  exit 1
fi

TMPDIR="$(mktemp -d)"

on_exit() {
  rm -rf "${TMPDIR}"
}

trap on_exit EXIT

data="$(mktemp "${TMPDIR}/data.XXXXXX")"
if [[ -z "${arg_id_glob:-}" ]]; then
  sqlite3 "${TFCLI_DBFILE:-${HOME}/.cache/tfcli/tfcli.sqlite}" \
    ".mode json" \
    ".parameter set @TFCLI_CACHE_EXPIRY ${TFCLI_CACHE_EXPIRY:-8640000}" \
    ".parameter set @arg_id_value ${arg_id_value:-}" \
    ".timeout ${SQLITE_BUSY_TIMEOUT:-60000}" \
    "SELECT
      *
    FROM
      \"${arg_table}\"
    WHERE
      _DeletedAt < 0
      AND _Id = @arg_id_value
      AND datetime('now', (SELECT -(@TFCLI_CACHE_EXPIRY)||' seconds')) < datetime(_UpdatedAt, 'unixepoch');" 1>"${data}" 2>/dev/null || true
else
  sqlite3 "${TFCLI_DBFILE:-${HOME}/.cache/tfcli/tfcli.sqlite}" \
    ".mode json" \
    ".parameter set @TFCLI_CACHE_EXPIRY ${TFCLI_CACHE_EXPIRY:-8640000}" \
    ".parameter set @arg_id_glob ${arg_id_glob:-}" \
    ".timeout ${SQLITE_BUSY_TIMEOUT:-60000}" \
    "SELECT
      *
    FROM
      \"${arg_table}\"
    WHERE
      _DeletedAt < 0
      AND _Id GLOB @arg_id_glob
      AND datetime('now', (SELECT -(@TFCLI_CACHE_EXPIRY)||' seconds')) < datetime(_UpdatedAt, 'unixepoch');" 1>"${data}" 2>/dev/null || true
fi

if [[ -s "${data}" ]]; then
  jq '.' < "${data}"
else
  jq --null-input '[]'
fi
