#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/teams#list-teams

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_names

arg_organization_name="${TF_CLOUD_ORGANIZATION:-}"
httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Organizations" --id-glob='*' | \
      jq --raw-output 'map("--organization-name=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Organizations" --id-glob='*' | \
      jq --raw-output 'map("--organization-name=\(.attributes | fromjson | .name)") | unique[]'
    tfc-helper-cache-get --table="Teams" --id-glob='*' | \
      jq --raw-output 'map("--team-id=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Teams" --id-glob='*' | \
      jq --raw-output 'map("--team-name=\(.attributes | fromjson | .name)") | unique[]'
    exit 0
    ;;
  "--debug" )
    set -x
    ;;
  "--force" ) # option: refresh cache
    :
    ;;
  "--help" ) # option: display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--names" | "--names="* ) # option: if specified, restricts results to a team with a matching name. If multiple comma separated values are specified, teams matching any of the names are returned.
    if [[ "$1" == *"="* ]]; then
      arg_names="${1#*=}"
    else
      arg_names="${2:-}"
      shift 1
    fi
    ;;
  "--organization-name" | "--organization-name="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_organization_name="${1#*=}"
    else
      arg_organization_name="${2:-}"
      shift 1
    fi
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -n "${arg_names:-}" ]]; then
  httpclient_args+=("--get" "--data" "filter[names]=${arg_names}")
fi

if [[ -z "${arg_organization_name:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: organization name was not given"
  exit 1
fi

# https://www.terraform.io/cloud-docs/api-docs/teams#list-teams
tfc-helper-httpclient --request-path="/organizations/${arg_organization_name}/teams" "${httpclient_args[@]}" | \
  tfc-helper-cache-set --table="Teams"
