#!/usr/bin/env bash
# summary: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/configuration-versions#show-a-configuration-version

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_configuration_version_id

httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="ConfigurationVersions" --id-glob='*' | \
      jq --raw-output 'map("--configuration-version-id=\(.id)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--configuration-version-id" | "--configuration-version-id="* ) # option: Configuration Version ID
    if [[ "$1" == *"="* ]]; then
      arg_configuration_version_id="${1#*=}"
    else
      arg_configuration_version_id="${2:-}"
      shift 1
    fi
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_configuration_version_id:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: configuration version id was not given"
  exit 1
fi

# https://developer.hashicorp.com/terraform/cloud-docs/api-docs/configuration-versions#show-a-configuration-version
tfc-helper-httpclient --request-path="/configuration-versions/${arg_configuration_version_id}" "${httpclient_args[@]}" --no-paginate
