#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/private-registry/providers#get-a-provider

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_name
unset arg_namespace
unset arg_registry_name

arg_organization_name="${TF_CLOUD_ORGANIZATION:-}"
httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Organizations" --id-glob='*' | \
      jq --raw-output 'map("--organization-name=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Organizations" --id-glob='*' | \
      jq --raw-output 'map("--organization-name=\(.attributes | fromjson | .name)") | unique[]'
#   tfc-helper-cache-get --table="RegistryProviders" --id-glob='*' | \
#     jq --raw-output 'map([.id // "", (.attributes // {} | fromjson | .name // "")][]) | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--name" | "--name="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_name="${1#*=}"
    else
      arg_name="${2:-}"
      shift 1
    fi
    ;;
  "--namespace" | "--namespace="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_namespace="${1#*=}"
    else
      arg_namespace="${2:-}"
      shift 1
    fi
    ;;
  "--organization-name" | "--organization-name="* ) # option: Organization name
    if [[ "$1" == *"="* ]]; then
      arg_organization_name="${1#*=}"
    else
      arg_organization_name="${2:-}"
      shift 1
    fi
    ;;
  "--registry-name" | "--registry-name="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_registry_name="${1#*=}"
    else
      arg_registry_name="${2:-}"
      shift 1
    fi
    ;;
  "--verbose" ) # option: Enable verbose output
    export VERBOSE=1
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_organization_name:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: organization name was not given"
  exit 1
fi

if [[ -z "${arg_registry_name:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: registry name was not given"
  exit 1
fi

if [[ -z "${arg_namespace:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: namespace was not given"
  exit 1
fi

if [[ -z "${arg_name:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: name was not given"
  exit 1
fi

# https://www.terraform.io/cloud-docs/api-docs/private-registry/providers#get-a-provider
tfc-helper-httpclient --request-path="/organizations/${arg_organization_name}/registry-providers/${arg_registry_name}/${arg_namespace}/${arg_name}" "${httpclient_args[@]}" --no-paginate | \
  tfc-helper-cache-set --partial --table="RegistryProviders"
