#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

arg_organization_name="${TF_CLOUD_ORGANIZATION:-}"
httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--debug" )
    set -x
    ;;
  "--help" ) # option: display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--organization-name" | "--organization-name="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_organization_name="${1#*=}"
    else
      arg_organization_name="${2:-}"
      shift 1
    fi
    ;;
  * )
    httpclient_args+=("${1:-}")
    ;;
  esac
  shift 1
done

if [[ -z "${arg_organization_name:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: organization name was not given"
  exit 1
fi

# https://www.terraform.io/cloud-docs/api-docs/vcs-events#list-vcs-events
tfc-helper-httpclient --request-path="/organizations/${arg_organization_name}/vcs-events" "${httpclient_args[@]}" | \
  tfc-helper-cache-set --table="VcsEvents"
