#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/agents#show-an-agent

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_agent_id

httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Agents" --id-glob='*' | \
      jq --raw-output 'map("--agent-id=\(.id)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--agent-id" | "--agent-id="* ) # option: Agent ID
    if [[ "$1" == *"="* ]]; then
      arg_agent_id="${1#*=}"
    else
      arg_agent_id="${2:-}"
      shift 1
    fi
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_agent_id:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: agent id was not given"
  exit 1
fi

# https://www.terraform.io/cloud-docs/api-docs/agents#show-an-agent
tfc-helper-httpclient --request-path="/agents/${arg_agent_id}" "${httpclient_args[@]}" --no-paginate | \
  tfc-helper-cache-set --table="Agents"
