#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/variable-sets#list-variable-set

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_workspace_id

arg_organization_name="${TF_CLOUD_ORGANIZATION:-}"
arg_workspace_name="${TF_WORKSPACE:-}"
httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Organizations" --id-glob='*' | \
      jq --raw-output 'map("--organization-name=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Organizations" --id-glob='*' | \
      jq --raw-output 'map("--organization-name=\(.attributes | fromjson | .name)") | unique[]'
    tfc-helper-cache-get --table="Workspaces" --id-glob='*' | \
      jq --raw-output 'map("--workspace-id=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Workspaces" --id-glob='*' | \
      jq --raw-output 'map("--workspace-name=\(.attributes | fromjson | .name)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--organization-name" | "--organization-name="* ) # option: Organization name
    if [[ "$1" == *"="* ]]; then
      arg_organization_name="${1#*=}"
    else
      arg_organization_name="${2:-}"
      shift 1
    fi
    ;;
  "--verbose" ) # option: Enable verbose output
    export VERBOSE=1
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  "--workspace-id" | "--workspace-id="* ) # option: Workspace ID
    if [[ "$1" == *"="* ]]; then
      arg_workspace_id="${1#*=}"
    else
      arg_workspace_id="${2:-}"
      shift 1
    fi
    ;;
  "--workspace-name" | "--workspace-name="* ) # option: Workspace name
    if [[ "$1" == *"="* ]]; then
      arg_workspace_name="${1#*=}"
    else
      arg_workspace_name="${2:-}"
      shift 1
    fi
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_workspace_id:-}" ]]; then
  if [[ -z "${arg_workspace_name:-}" ]]; then
    :
  else
    arg_workspace_id="$(tfc-get-workspace --workspace-name="${arg_workspace_name}" | jq --raw-output '.data.id')"
  fi
fi

# https://www.terraform.io/cloud-docs/api-docs/variable-sets#list-variable-set
if [[ -z "${arg_workspace_id:-}" ]]; then
  if [[ -z "${arg_organization_name:-}" ]]; then
    tfc-helper-logger --level=error "${0##*/}: organization name was not given"
    exit 1
  fi
  tfc-helper-httpclient --request-path="/organizations/${arg_organization_name}/varsets" "${httpclient_args[@]}" | \
    tfc-helper-cache-set --table="VariableSets"
else
  tfc-helper-httpclient --request-path="/workspaces/${arg_workspace_id}/varsets" "${httpclient_args[@]}" | \
    tfc-helper-cache-set --partial --table="VariableSets"
fi
