#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/agents#show-an-agent-pool

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_agent_pool_id
unset arg_agent_pool_name

httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="AgentPools" --id-glob='*' | \
      jq --raw-output 'map("--agent-pool-id=\(.id)") | unique[]'
    tfc-helper-cache-get --table="AgentPools" --id-glob='*' | \
      jq --raw-output 'map("--agent-pool-name=\(.attributes | fromjson | .name)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--agent-pool-id" | "--agent-pool-id="* | "--apool-id" | "--apool-id="* ) # option: Agent Pool ID
    if [[ "$1" == *"="* ]]; then
      arg_agent_pool_id="${1#*=}"
    else
      arg_agent_pool_id="${2:-}"
      shift 1
    fi
    ;;
  "--agent-pool-name" | "--agent-pool-name="* | "--apool-name" | "--apool-name="* ) # option: Agent Pool name
    if [[ "$1" == *"="* ]]; then
      arg_agent_pool_name="${1#*=}"
    else
      arg_agent_pool_name="${2:-}"
      shift 1
    fi
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_agent_pool_id:-}" ]]; then
  if [[ -z "${arg_agent_pool_name:-}" ]]; then
    :
  else
    arg_agent_pool_id="$(tfc-list-agent-pools | jq --arg name "${arg_agent_pool_name}" --raw-output '.data | map(select(.attributes.name == $name))[].id')"
  fi
  if [[ -z "${arg_agent_pool_id:-}" ]]; then
    tfc-helper-logger --level=error "${0##*/}: agent pool id was not given"
    exit 1
  fi
fi

# https://www.terraform.io/cloud-docs/api-docs/agents#show-an-agent-pool
tfc-helper-httpclient --request-path="/agent-pools/${arg_agent_pool_id}" "${httpclient_args[@]}" --no-paginate | \
  tfc-helper-cache-set --partial --table="AgentPools"
