#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/plan-exports#delete-exported-plan-data

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_plan_export_id

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    shift 1
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="PlanExports" --id-glob='*' | \
      jq --raw-output 'map("--plan-export-id=\(.id)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--plan-export-id" | "--plan-export-id="* ) # option: Plan Export ID
    if [[ "$1" == *"="* ]]; then
      arg_plan_export_id="${1#*=}"
    else
      arg_plan_export_id="${2:-}"
      shift 1
    fi
    ;;
  "--verbose" | "-v" ) # option: Enable verbose output
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_plan_export_id:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: plan export id was not given"
  exit 1
fi

# https://www.terraform.io/cloud-docs/api-docs/plan-exports#delete-exported-plan-data
tfc-helper-httpclient --request-path="/plan-exports/${arg_plan_export_id}" --request DELETE --no-paginate
