#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/teams#show-team-information

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_team_id
unset arg_team_name

httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Teams" --id-glob='*' | \
      jq --raw-output 'map("--team-id=\(.id)") | unique[]'
    tfc-helper-cache-get --table="Teams" --id-glob='*' | \
      jq --raw-output 'map("--team-name=\(.attributes | fromjson | .name)") | unique[]'
    exit 0
    ;;
  "--debug" )
    set -x
    ;;
  "--help" ) # option: display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--team-id" | "--team-id="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_team_id="${1#*=}"
    else
      arg_team_id="${2:-}"
      shift 1
    fi
    ;;
  "--team-name" | "--team-name="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_team_name="${1#*=}"
    else
      arg_team_name="${2:-}"
      shift 1
    fi
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_team_id:-}" ]]; then
  if [[ -z "${arg_team_name:-}" ]]; then
    :
  else
    arg_team_id="$(tfc-helper-cache-get --table="Teams" --id-glob='*' | \
      jq --arg name "${arg_team_name}" --raw-output 'map(select(.attributes | fromjson | .name == $name))[].id' \
    )"
  fi
  if [[ -z "${arg_team_id:-}" ]]; then
    tfc-helper-logger --level=error "${0##*/}: team id was not given"
    exit 1
  fi
fi

# https://www.terraform.io/cloud-docs/api-docs/teams#show-team-information
tfc-helper-httpclient --request-path="/teams/${arg_team_id}" "${httpclient_args[@]}" --no-paginate | \
  tfc-helper-cache-set --table="Teams"
