#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/applies#show-an-apply

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_apply_id

httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--apply-id" | "--apply-id="* ) # option: Apply ID
    if [[ "$1" == *"="* ]]; then
      arg_apply_id="${1#*=}"
    else
      arg_apply_id="${2:-}"
      shift 1
    fi
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Applies" --id-glob='*' | \
      jq --raw-output 'map("--apply-id=\(.id)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--verbose" ) # option: Enable verbose output
    export VERBOSE=1
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_apply_id:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: apply id was not given"
  exit 1
fi

# https://www.terraform.io/cloud-docs/api-docs/applies#show-an-apply
tfc-helper-httpclient --request-path="/applies/${arg_apply_id}" "${httpclient_args[@]}" --no-paginate
