#!/usr/bin/env bash
# summary: https://developer.hashicorp.com/terraform/cloud-docs/api-docs/oauth-clients#show-an-oauth-client

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_oauth_client_id
unset arg_oauth_client_name

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    shift 1
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="OAuthClients" --id-glob='*' | \
      jq --raw-output 'map("--oauth-client-id=\(.id)") | unique[]'
    tfc-helper-cache-get --table="OAuthClients" --id-glob='*' | \
      jq --raw-output 'map("--oauth-client-name=\(.attributes | fromjson | .name)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--oauth-client-id" | "--oaht-client-id="* | "--oc-id" | "--oc-id="* ) # option: OAuth Client ID
    if [[ "$1" == *"="* ]]; then
      arg_oauth_client_id="${1#*=}"
    else
      arg_oauth_client_id="${2:-}"
      shift 1
    fi
    ;;
  "--oauth-client-name" | "--oauth-client-name="* | "--oc-name" | "--oc-name="* ) # option: OAuth Client name
    if [[ "$1" == *"="* ]]; then
      arg_oauth_client_name="${1#*=}"
    else
      arg_oauth_client_name="${2:-}"
      shift 1
    fi
    ;;
  "--verbose" | "-v" ) # option: Enable verbose output
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_oauth_client_id:-}" ]]; then
  if [[ -z "${arg_oauth_client_name:-}" ]]; then
    :
  else
    arg_oauth_client_id="$(tfc-list-oauth-clients | jq --arg name "${arg_oauth_client_name}" --raw-output '.data | map(select(.attributes.name == $name))[].id')"
  fi
  if [[ -z "${arg_oauth_client_id:-}" ]]; then
    tfc-helper-logger --level=error "${0##*/}: oauth client id was not given"
    exit 1
  fi
fi

# https://developer.hashicorp.com/terraform/cloud-docs/api-docs/oauth-clients#show-an-oauth-client
tfc-helper-httpclient --request-path="/oauth-clients/${arg_oauth_client_id}" --no-paginate | \
  tfc-helper-cache-set --partial --table="OAuthClients"
