#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_partial
unset arg_table

arg_id_key="id"

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    shift 1
    break
    ;;
  "--complete" )
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    exit 0
    ;;
  "--id-key" | "--id-key="* ) # option: JSON field name to be used for primary key
    if [[ "$1" == *"="* ]]; then
      arg_id_key="${1#*=}"
    else
      arg_id_key="${2:-}"
      shift 1
    fi
    ;;
  "--partial" | "--no-partial" ) # option: Specify if cache is partial content or not
    if [[ "$1" == "--no-"* ]]; then
      arg_partial=
    else
      arg_partial=1
    fi
    ;;
  "--table" | "--table="* ) # option: SQLite3 table name used for caching
    if [[ "$1" == *"="* ]]; then
      arg_table="${1#*=}"
    else
      arg_table="${2:-}"
      shift 1
    fi
    ;;
  "--verbose" | "-v" ) # option: Enable verbose output
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_table:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: missing required option: --table"
  exit 1
fi

TMPDIR="$(mktemp -d)"

on_exit() {
  rm -rf "${TMPDIR}"
}

trap on_exit EXIT

raw_data="$(mktemp "${TMPDIR}/raw_data.XXXXXX")"

if jq '.' > "${raw_data}"; then
  data="$(mktemp "${TMPDIR}/data.XXXXXX")"
  jq --arg PROGRAM_NAME "${0##*/}" --arg id_key "${arg_id_key}" \
    'if (.data | type) == "array" then
      .data
    elif (.data | type) == "object" then
      [.data]
    else
      error("\($PROGRAM_NAME): unsupported data type: \(.data | type)")
    end | map(. * {
      _Id: (.[$id_key] | tostring),
      _CreatedAt: now,
      _UpdatedAt: now,
      _DeletedAt: -1
    })' < "${raw_data}" > "${data}"
  if [[ "${TFCLI_DISABLE_CACHE:-false}" == true ]]; then
    : # skip managing cache entries if `TFCCLI_DISABLE_CACHE=true` was set
  else
    json2sqlite3_opts=()
    if [[ -z "${arg_partial:-}" ]]; then
      json2sqlite3_opts+=("--soft-delete")
    else
      json2sqlite3_opts+=("--no-soft-delete")
    fi
    json2sqlite3 \
      --primary-key-column="_Id:TEXT" \
      --created-column="_CreatedAt:NUMERIC" \
      --updated-column="_UpdatedAt:NUMERIC" \
      --deleted-column="_DeletedAt:NUMERIC" \
      --preserve-created \
      "${json2sqlite3_opts[@]}" \
      "${TFCLI_DBFILE:-${HOME}/.cache/tfcli/tfcli.sqlite}" \
      "${arg_table}" < "${data}" > /dev/null
  fi

  # behave as write-through cache
  jq '.' "${raw_data}"
else
  tfc-helper-logger --level=error "${0##*/}: invalid JSON"
  exit 1
fi
