#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/run#get-run-details

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_run_id

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    shift 1
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="Runs" --id-glob='*' | \
      jq --raw-output 'map("--run-id=\(.id)") | unique[]'
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--run-id" | "--run-id="* ) # option: Run ID
    if [[ "$1" == *"="* ]]; then
      arg_run_id="${1#*=}"
    else
      arg_run_id="${2:-}"
      shift 1
    fi
    ;;
  "--verbose" | "-v" ) # option: Enable verbose output
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_run_id:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: run id was not given"
  exit 1
fi

# https://www.terraform.io/cloud-docs/api-docs/run#get-run-details
tfc-helper-httpclient --request-path="/runs/${arg_run_id}" --no-paginate
