#!/usr/bin/env bash

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

unset arg_plan_export_id

httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    tfc-helper-cache-get --table="PlanExports" --id-glob='*' | \
      jq --raw-output 'map("--plan-export-id=\(.id)") | unique[]'
    exit 0
    ;;
  "--debug" )
    set -x
    ;;
  "--help" ) # option: display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--plan-export-id" | "--plan-export-id="* ) # option: TODO
    if [[ "$1" == *"="* ]]; then
      arg_plan_export_id="${1#*=}"
    else
      arg_plan_export_id="${2:-}"
      shift 1
    fi
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

if [[ -z "${arg_plan_export_id:-}" ]]; then
  tfc-helper-logger --level=error "${0##*/}: plan export id was not given"
  exit 1
fi

# https://www.terraform.io/cloud-docs/api-docs/plan-exports#show-a-plan-export
tfc-helper-httpclient --request-path="/plan-exports/${arg_plan_export_id}" "${httpclient_args[@]}" --no-paginate
