#!/usr/bin/env bash
# summary: https://www.terraform.io/cloud-docs/api-docs/account#get-your-account-details

set -euo pipefail

[[ -z "${DEBUG:-}" ]] || set -x

httpclient_args=()

while [[ $# -gt 0 ]]; do
  case "${1:-}" in
  "--" )
    break
    ;;
  "--complete" )
    tfc-helper-complete "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--debug" ) # option: Enable debug output
    set -x
    ;;
  "--help" ) # option: Display help message
    tfc-helper-help "${BASH_SOURCE##*/}"
    exit 0
    ;;
  "--verbose" ) # option: Enable verbose output
    export VERBOSE=1
    export VERBOSITY="$(( VERBOSITY + 1 ))"
    ;;
  * )
    tfc-helper-logger --level=error "${0##*/}: unrecognized option: ${1:-}"
    exit 1
    ;;
  esac
  shift 1
done

# https://www.terraform.io/cloud-docs/api-docs/account#get-your-account-details
tfc-helper-httpclient --request-path="/account/details" "${httpclient_args[@]}" --no-paginate | \
  tfc-helper-cache-set --table="AccountDetails"
